name: 'Manifest PR handler'
description: 'Handles manifest PR related tasks'
inputs:
  target-repo:
    required: false
    type: string
    default: nrfconnect/sdk-nrf
    description: 'target repository for manifest PR'
  base-branch:
    required: false
    type: string
    default: main
    description: 'base/target branch for manifest PR'
  forked-repo:
    required: false
    type: string
    default: nordicbuilder/sdk-nrf
    description: 'forked repository where changes are pushed'
  skip-string:
    required: false
    type: string
    default: manifest-pr-skip
  manifest-pr-title-details:
    required: false
    type: string
    default: 'Update revision'
    description: 'Input to the manifest PR title: "manifest: <repo>: <manifest-pr-title-details>"'
  token:
    required: true
    type: string
  draft-pr:
    required: false
    type: boolean
    default: false
    description: 'If set, the manifest PR will be created as a draft PR'

runs:
  using: "composite"
  steps:
    - name: Add external label
      uses: carlescufi/action-contribs@main
      with:
        github-token: ${{ inputs.token }}
        command: 'external'
        labels: 'external'

    - name: Setup Python
      shell: bash
      run: |
        pip3 install setuptools wheel
        pip3 install -r "${{ github.action_path }}/requirements.txt"

    - name: Run manifest PR handler
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GH_TOKEN: ${{ inputs.token }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
      run: |
        python3 "${{ github.action_path }}/action.py" \
          --target-repo "${{ inputs.target-repo }}" \
          --base-branch "${{ inputs.base-branch }}" \
          --forked-repo "${{ inputs.forked-repo }}" \
          --skip-string "${{ inputs.skip-string }}" \
          --manifest-pr-title-details "${{ inputs.manifest-pr-title-details }}" \
          ${{ inputs.draft-pr == 'true' && '--draft-pr' || '' }}
